import type { Metadata } from "next";
import { fontSuit, fontSuisse } from "@/app/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSuit.variable} ${fontSuisse.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
