import type { Metadata } from "next";
import { fontSuit, fontSuisse } from "@/styles/font";
import "@/styles/globals.css";
import { cn } from "@/common/utils/tailwind";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(fontSuit.variable, fontSuisse.variable, "antialiased")}>{children}</body>
		</html>
	);
}
