export enum ENUM_PRODUCT_FILE_TYPE {
	PRODUCT_COVER_IMAGE = "PRODUCT_COVER_IMAGE",
	PRODUCT_AUDIO_FILE = "PRODUCT_AUDIO_FILE",
	PRODUCT_ZIP_FILE = "PRODUCT_ZIP_FILE",
}

export enum ENUM_PRODUCT_TYPE {
	BEAT = "BEAT",
	ACAPELA = "ACAPELA",
}

export enum ENUM_PRODUCT_SORT {
	RECENT = "RECENT",
	RECOMMEND = "RECOMMEND",
}
