export enum ENUM_AWS_STATUS_CODE_ERROR {
	UPLOAD_PATH_NOT_FOUND_ERROR = 1300,
	S3_UPLOAD_ERROR = 1301,
	CLOUDFRONT_INVALID_URL_ERROR = 1302,
	CLOUDFRONT_SIGN_URL_ERROR = 1303,
	CLOUDFRONT_SIGN_COOKIE_ERROR = 1304,
}
