export enum ENUM_S3_UPLOAD_TYPE {
    WORKSPACE_PROFILE = 'WORKSPACE_PROFILE',
    USER_PROFILE = 'USER_PROFILE',
    VOICE = 'VOICE',
    RESUME = 'RESUME',
    CONNECT_LOGO = 'CONNECT_LOGO',
    RECORDING_FILE = 'RECORDING_FILE',
}
