export enum ENUM_PAGINATION_ORDER_DIRECTION_TYPE {
    ASC = 1,
    DESC = -1,
}

export enum ENUM_PAGINATION_FILTER_DATE_TIME_OPTIONS {
    START_OF_DAY = 'START_OF_DAY',
    END_OF_DAY = 'END_OF_DAY',
}
